### ISSUE TITLE
0.8.1 breaks on node.

### ISSUE THREAD

**Issue by sramam** [SitePen/remap-istanbul#109]
I just upgraded to 0.8.1 and it seems broken on node -

This is a sample script that works with 0.8.0

```
var remapper = require('remap-istanbul')
var cov = remapper.loadCoverage('./coverage/coverage.json')
```

with 0.8.1:

```
~/my_project/node_modules/remap-istanbul/lib/main.js:57
})(define);
   ^

ReferenceError: define is not defined
    at Object.<anonymous> (~/myproject/node_modules/remap-istanbul/lib/main.js:57:4)

```

Looking at the documentation, it seems this might be the change required:

```
var loadCoverage = require('remap-istanbul/lib/loadCoverage').default
var cov = remapper.loadCoverage('./coverage/coverage.json')
```

But get the same error
```
~/my_project/node_modules/remap-istanbul/lib/loadCoverage.js:58
})(define);
   ^

ReferenceError: define is not defined
    at Object.<anonymous> (~/my_project/node_modules/remap-istanbul/lib/loadCoverage.js:58:4)
```

I'm out of time to dig deeper -  reverting to 0.8.0 and moving on.
May I suggest using umd modules? life will be easier all around.

**Comment by jdonaghue** [comment]
@sramam this is fixed with `0.8.2`. I just published to npm. Thanks!

**Comment by sramam** [comment]
Thanks for the quick turn around. 
May I suggest using [SemVer](http://semver.org/), to prevent unintended dependency breakage? This was an API change on a patch release that caused much distraction.

**Comment by dylans** [comment]
Hi @sramam, we do follow semver... this is a pre-1.0 release so API changes may still occur across point releases.

**Comment by dylans** [comment]
So the issue we have is 0.8.0 fixed a number of things, and regressed for a number of other users. 0.8.1 and 0.8.2 attempted to fix that and have now regressed things for people where 0.8.0 was working fine. Apologies, we're working to fix asap. We'll likely number whatever the fix is as 0.9.

**Comment by sramam** [comment]
ok. Thanks for a very useful project.
